jobs:
  include:
    - stage: "build time"
      script:
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker build -t udagram-api-user ./udagram-api-user
        - docker build -t udagram-frontend ./udagram-frontend
        - docker build -t reverseproxy ./udagram-reverseproxy

        # - stage: "tagging images"
        #   script:
        - docker tag udagram-api-feed cuongph10/udagram-api-feed:latest
        - docker tag udagram-api-user cuongph10/udagram-api-user:latest
        - docker tag udagram-frontend cuongph10/udagram-frontend:latest
        - docker tag reverseproxy cuongph10/reverseproxy:latest

        # - stage: "login to docker hub"
        #   script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # - stage: "Push images to docker hub"
        #   script:
        - docker push cuongph10/udagram-api-feed:latest
        - docker push cuongph10/udagram-api-user:latest
        - docker push cuongph10/udagram-frontend:latest
        - docker push cuongph10/reverseproxy:latest
